trigger:
  branches:
    include:
      - SPRINT

  paths:
    include:
    - futurenhs.automation/*

jobs:
- job:
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
    demands: npm

  steps:
    - script: |
        echo dir
      displayName: 'Command Line Script'
      workingDirectory: $(Build.SourcesDirectory)

    - task: Npm@1
      displayName: 'Npm install'
      inputs:
       command: 'install'
       workingDir: '$(Build.SourcesDirectory)/futurenhs.app'


    - script: 'npm test $(TESTSUITE)'
      displayName: 'Execute Tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/wdio-*.log'
      inputs:
        testResultsFiles: '**/wdio-*.log'
